name: Axis-CI

on:
  push:
    paths:
      - '**'
      - '!.github/workflows/example-checks.yml'
      - '!README.md'
      - '!LICENSE'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: qemu cross compiler
      run: |
         docker run --rm --privileged multiarch/qemu-user-static --credential yes --persistent yes

    - name: Build camera-calibration application
      run: |
        cd ./camera-calibration
        docker build -t axisecp/camera-calibration .
